version: "3.1"

services:
  database:
    image: postgres:13
    container_name: fusionadapter-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: timeline
      POSTGRES_USER: timeline
      POSTGRES_PASSWORD: asd123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
